import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SearchContainer from "@/components/SearchContainer";
import PathSyncListener from "@/components/PathSyncListener";
import PageWrapper from "@/components/layouts/home/PageWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased font-sans"
    >
      <body className="min-h-screen w-full m-0 p-0 bg-[#b1b3b5] overflow-x-hidden select-none">
        <PathSyncListener />
        <header>
          <SearchContainer />
        </header>
        <main className="flex">
          <aside>
            <Sidebar />
          </aside>
          <section className="w-full min-w-0 pt-2 overflow-x-hidden">
            <PageWrapper>
              {children}
            </PageWrapper>
          </section>
        </main>
      </body>
    </html>
  );
}
